### ISSUE TITLE
Fix error occuring when setting the spoilage of an item to 0H.

### ISSUE THREAD

**Issue by dmccoystephenson** [Dans-Plugins/FoodSpoilage#207]
[19:38:28 ERROR]: Could not pass event EntityPickupItemEvent to FoodSpoilage v3.0.0
java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
        at java.time.Duration.parse(Duration.java:419) ~[?:?]
        at spoilagesystem.config.LocalConfigService.getTime(LocalConfigService.java:41) ~[FoodSpoilage.jar:?]
        at spoilagesystem.timestamp.LocalTimeStampService.assignTimeStamp(LocalTimeStampService.java:63) ~[FoodSpoilage.jar:?]
        at spoilagesystem.listeners.EntityPickupItemListener.onEntityPickupItem(EntityPickupItemListener.java:23) ~[FoodSpoilage.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2970.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1691]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:464) ~[?:?]
        at net.minecraft.world.entity.player.Player.touch(Player.java:670) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:636) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3033) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:307) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:693) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:355) ~[?:?]
        at net.minecraft.network.[Connection](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+connection).tick([Connection](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+connection).java:577) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[purpur-1.19.jar:git-Purpur-1691]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1691]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1691]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1691]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1691]
        at java.lang.[Thread](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+thread).run([Thread](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+thread).java:833) ~[?:?]

**Comment by dmccoystephenson** [comment]
Resolved in PR #244.
